common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: rossgeesman
  password: 

development:
  <<: *common
  database: tweetr_dev
test:
  <<: *common
  database: tweetr_test

production:
  <<: *common
  database: tweetr_prod
